---
- name: Define configuracao do servidor Memcached
  template:
    src: memcached.conf.j2
    dest: /etc/memcached.conf 
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart Memcached
  tags: memcached
