---
- name: Instala o pacote python3-memcache
  apt:
    name: python3-memcache
    update_cache: yes
    
- name: Instala o Memcached Server
  apt:
    name: memcached
    update_cache: yes
  notify:
    - Start Memcached
  tags: memcached
- name: Inicia e ativa na inicializacao o servico Memcached
  systemd:
    name: memcached
    state: started
    enabled: yes
  tags: memcached    
